### ISSUE TITLE
[Azure] Error: VM size is not valid

### ISSUE THREAD

**Issue by JasonDing0401** [skyplane-project/skyplane#481]
The command I ran that caused this error was `skyplane cp -y -r https://aucent.blob.core.windows.net/fake-image-net/fake_imagenet/ s3://eu-west-3/fake_imagenet_5/`, which tried to copy azure blob files to s3 bucket.
The full error trace and the client log are attached:
[error.txt](https://github.com/skyplane-project/skyplane/files/9274415/error.txt)
[client.log](https://github.com/skyplane-project/skyplane/files/9274416/client.log)

**Comment by JasonDing0401** [comment]
Skyplane's default azure_instance_class setting is "Standard_D32_v5", which is included in the list of valid VMs (also tried "Standard_D32_v4"), but I still got the same error.

**Comment by parasj** [comment]
The resolution here is better error handling in #474.
