### ISSUE TITLE
Azure transfer failed on bucket check

### ISSUE THREAD

**Issue by parasj** [skyplane-project/skyplane#482]
Reported by @romilbhardwaj

See trace at: https://gist.github.com/romilbhardwaj/7b8b84cf30952d7cf7965d7ec9b3d7ee

**Comment by romilbhardwaj** [comment]
Just to add, I also tried `skyplane cp s3://romil-sky-test https://romiltest.blob.core.windows.net/data` but that also failed with the same error

**Comment by abiswal2001** [comment]
@romilbhardwaj I pushed a change to main with refactored Azure authentication. Does this change fix this issue for you?

**Comment by parasj** [comment]
@romilbhardwaj Another bump to see if this is fixed for you -- any update would help!

**Comment by romilbhardwaj** [comment]
Ah sorry, I won't be able to try it out this week. but please feel free to close this issue if it is fixed in your testing.
