### ISSUE TITLE
[S3] `MissingBucketException` for bucket accessible with AWS CLI but not owned by same account

### ISSUE THREAD

**Issue by sarahwooders** [skyplane-project/skyplane#510]
I'm able to access a bucket (in region 'us-east-1') and am trying to move it to another account which I have access to but do not down. However I get an exception saying the source bucket does not exist. 

I suspect this is a bug because we rely on listing the account's buckets to check if the bucket exists - however a user may have access to a bucket they can copy from even if they are not the bucket owner: https://github.com/skyplane-project/skyplane/blob/main/skyplane/obj_store/s3_interface.py#L47. I run `aws s3api list-buckets` and the source bucket does not appear, which is probably why there is an error.  

We should find a way to check if a bucket exists even if the bucket is not owned by the user - e.g. by listing bucket contents and seeing if that throws an error, or using an AWS CLI command.

**Comment by narang-amit** [comment]
Think [get-bucket-acl](https://docs.aws.amazon.com/cli/latest/reference/s3api/get-bucket-acl.html) might do the trick? Would you like me to take a stab at it or are you working on it already?

**Comment by parasj** [comment]
Hey @narang-amit, any progress on this issue? Happy to sync quickly about this over Slack!

**Comment by narang-amit** [comment]
Hey! Got started, been a bit busy with interviewing. Should be able to take a stab at it tomorrow. Will update.

**Comment by parasj** [comment]
Thanks. Note that https://github.com/skyplane-project/skyplane/issues/528 is now fixed, and I think these may be similar issues. The fix was to improve logic around checking for bucket existence.

**Comment by sarahwooders** [comment]
I get a different error on this transfer now, so I can add that and we can close this issue?
