### ISSUE TITLE
Installing skyplane on ARM cores

### ISSUE THREAD

**Issue by ShishirPatil** [skyplane-project/skyplane#517]
The recommended `pip install skyplane` fails on ARM cores. 

Command to recreate: `pip install skyplane` 

Error:

```
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/358.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/358.
from: can't read /var/mail/pip._internal.cli.main
.py3/bin/pip: line 7: syntax error near unexpected token `('
.py3/bin/pip: line 7: `    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])'
```

**Comment by parasj** [comment]
@ShishirPatil See the note about M1 Macs here: https://github.com/skyplane-project/skyplane#installation

Does the alternative grpcio command succeed?

**Comment by parasj** [comment]
Based on [this StackOverflow post](https://stackoverflow.com/questions/19507096/python-error-import-unable-to-open-x-server), this looks like an issue with pip running commands in the shell instead of Python. Closing.
