### ISSUE TITLE
Failed to transfer data from s3 bucket with public access to gcs bucket

### ISSUE THREAD

**Issue by Michaelvll** [skyplane-project/skyplane#528]
I have a s3 bucket that has all the ACL permission open to public and make all objects in it public by manually selecting them in the web console (as shown below).
![image](https://user-images.githubusercontent.com/6753189/189273857-bcd9faa8-f358-4664-99e1-6b2e0ed80a86.png)

It seems that I can transfer the data from that s3 bucket to a gs bucket by:
```
gsutil -m cp -r s3://mybucket gs://mybucket-gcp
```

However, `skyplane-nightly` complains about the permission issue, as shown in the [test.log](https://github.com/skyplane-project/skyplane/files/9532401/test.log) file (I have hidden the bucket name in the log). I am guessing the proble was caused by the bucket does not have the [GetBucketLocation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketLocation.html) permission, as I did observe that the data transfer service failed as well (unfortunately, I lost the log).

**Comment by Michaelvll** [comment]
After adding the following policy to the bucket, it works now:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "acm-pca.amazonaws.com"
            },
            "Action": [
                "s3:GetBucketAcl",
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::mybucket/*",
                "arn:aws:s3:::mybucket"
            ]
        }
    ]
}
```

**Comment by Michaelvll** [comment]
After adding the following bucket policy, it seems work now:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "acm-pca.amazonaws.com"
            },
            "Action": [
                "s3:GetBucketAcl",
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::mybucket/*",
                "arn:aws:s3:::mybucket"
            ]
        }
    ]
}
```

**Comment by Michaelvll** [comment]
After applying the following policy to the bucket, it seems working now:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "acm-pca.amazonaws.com"
            },
            "Action": [
                "s3:GetBucketAcl",
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::mybucket/*",
                "arn:aws:s3:::mybucket"
            ]
        }
    ]
}
```

**Comment by parasj** [comment]
@Michaelvll Apologies for the delay on this but it was a pretty major refactor to add support for public buckets. It's now merged to main so the transfer completes successfully. Let me know if there are any issues with it.
<img width="1289" alt="image (8)" src="https://user-images.githubusercontent.com/453850/191560595-75de689e-056d-48f7-a235-73b5c432208d.png">
