### ISSUE TITLE
[CLI] Merge `skyplane cp` and `skypane sync` implementation

### ISSUE THREAD

**Issue by ShishirPatil** [skyplane-project/skyplane#550]
The right design would be - Skyplane sync should draw up a list of chunks to transfer from source bucket to destination bucket and then call skyplane cp. A lot of duplicated code as of now.

**Comment by parasj** [comment]
I've minimized as much of the duplicated code as I can. What's left is the public CLI interface which will need to remain regardless of what we do. With #591, we can further eliminate duplicated code. Closing this for now.
