### ISSUE TITLE
Skyplane costs need to account for querying buckets, and instances

### ISSUE THREAD

**Issue by ShishirPatil** [skyplane-project/skyplane#551]
During a transfer, we inform the user what the estimated costs are. 
This needs to include a) cost of querying the buckets for list of objects, b) the total cost of VMs we provision.
I think we already include inter-continental transfer fees? If not, we got to include that too.

**Comment by parasj** [comment]
This is very hard to estimate:
1) RE querying the object store, we don't know how many times we will read or write to an object. This cost is also negligible so it won't meaningfully affect costs unless there are millions of objects.
2) We don't know how long VMs will be up, so we can't estimate the cost of them apriori.
