### ISSUE TITLE
Migrate to private IPs 

### ISSUE THREAD

**Issue by sarahwooders** [skyplane-project/skyplane#585]
Currently by Skyplane uses public IPs, so transfers within a single provider will unnecessarily go over the internet and be subject to stricter bandwidth limits. 

To fix this, I believe we need to modify https://github.com/skyplane-project/skyplane/blob/main/skyplane/compute/server.py#L266 to pass in the private IPs into `outgoing_ports`.

**Comment by parasj** [comment]
@lynnliu030 This was an earlier attempt at private IPs for GCP (profiling only, not data plane): https://github.com/skyplane-project/skyplane/pull/325/files

Mainly, you will need to at least do the following:
* Add a `private_ip` field to aws_cloud_provider, azure_cloud_provider and gcp_cloud_provider
* When constructing the dataplane in provision_gateways (replicator client), pass the private IP if the edge is a GCP to GCP edge
  * With regards to Azure, I'm not sure if we can use the private IP. This article may have some info: https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections?toc=%2Fazure%2Fvirtual-network%2Ftoc.json
* Update the profiling code for the throughput grid to use private IPs for GCP to GCP connections (see my PR)
