### ISSUE TITLE
Skyplane doesn't support `--all` flag for Azure

### ISSUE THREAD

**Issue by ShishirPatil** [skyplane-project/skyplane#588]
Any transfer involving Azure with `--reuse-gateways` followed by `skyplane deprovision` will leave orphaned resources. Skyplane deprovision should clean up VPNs, etc.

**Comment by parasj** [comment]
Can you provide an example of this? Skyplane deprovision should go and clean up associated resouces.

**Comment by sarahwooders** [comment]
Closing since stale
