### ISSUE TITLE
Fail to configure gcp region on ubuntu 20.04 python 3.8

### ISSUE THREAD

**Issue by dbickson** [skyplane-project/skyplane#599]
With the following error:

```
(3) Configuring GCP:
    Do you want to configure GCP support in Skyplane? [Y/n]: Y
    GCP credentials found in GCP CLI
    GCP credentials found, do you want to enable GCP support in Skyplane? [Y/n]: Y
    Enter the GCP project ID [flash-ward-346914]:
    Using GCP service account skyplane-manual
    Error saving GCP region config
    <HttpError 403 when requesting https://cloudresourcemanager.googleapis.com/v1/projects/flash-ward-346914:setIamPolicy?alt=json returned "Policy update access denied.". Details: "Policy update access denied.">
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/skyplane/cli/cli_impl/init.py", line 251, in load_gcp_config
    auth.save_region_config()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/skyplane/utils/imports.py", line 33, in wrapped
    return fn(*modules_imported, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/skyplane/compute/gcp/gcp_auth.py", line 32, in save_region_config
    service_account_credentials_file = self.service_account_credentials  # force creation of file
  File "/home/ubuntu/.local/lib/python3.8/site-packages/skyplane/compute/gcp/gcp_auth.py", line 68, in service_account_credentials
    self._service_account_email = self.create_service_account(self.service_account_name)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/skyplane/compute/gcp/gcp_auth.py", line 179, in create_service_account
    return retry_backoff(read_modify_write)  # retry loop needed for concurrent policy modifications
  File "/home/ubuntu/.local/lib/python3.8/site-packages/skyplane/utils/retry.py", line 30, in retry_backoff
    raise e
  File "/home/ubuntu/.local/lib/python3.8/site-packages/skyplane/utils/retry.py", line 27, in retry_backoff
    return fn()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/skyplane/compute/gcp/gcp_auth.py", line 176, in read_modify_write
    service.projects().setIamPolicy(resource=self.project_id, body={"policy": policy}).execute()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://cloudresourcemanager.googleapis.com/v1/projects/flash-ward-346914:setIamPolicy?alt=json returned "Policy update access denied.". Details: "Policy update access denied.">

    Disabling Google Cloud support

```

**Comment by sarahwooders** [comment]
Thanks for posting this @dbickson! Do the GCP CLI credentials you're using have permissions to create service accounts? Unfortunately, we have to create a Skyplane service account to use the Google XML API. 

If your GCP CLI credentials don't have sufficient permissions, do you have permissions to manually create a service account from the GCP console? You can create service accounts from "IAM & Admin" -> "Service Accounts". If that works,  can send more instructions for how to connect Skyplane with an existing service account.

**Comment by dbickson** [comment]
Hi @sarahwooders when looking at IAM-> service accounts in the gc console I see 
<img width="847" alt="Screen Shot 2022-10-11 at 7 02 16" src="https://user-images.githubusercontent.com/4495523/194994433-cea1b7aa-7677-4315-ac29-c07e58a53693.png">


skyplane-manual@flash-ward-346914.iam.gserviceaccount.com |   | skyplane-manual
-- | -- | --

**Comment by dbickson** [comment]
The ec2 region error was ```╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │      api_params = {}                                                                         │ │
│ │     error_class = <class 'botocore.exceptions.ClientError'>                                  │ │
│ │      error_code = 'UnauthorizedOperation'                                                    │ │
│ │  event_response = None                                                                       │ │
│ │         handler = <function inject_api_version_header_if_needed at 0x7f973c1dd040>           │ │
│ │            http = <botocore.awsrequest.AWSResponse object at 0x7f973b685c10>                 │ │
│ │ operation_model = OperationModel(name=DescribeRegions)                                       │ │
│ │  operation_name = 'DescribeRegions'                                                          │ │
│ │ parsed_response = {                                                                          │ │
│ │                   │   'Error': {                                                             │ │
│ │                   │   │   'Code': 'UnauthorizedOperation',                                   │ │
│ │                   │   │   'Message': 'You are not authorized to perform this operation.'     │ │
│ │                   │   },                                                                     │ │
│ │                   │   'ResponseMetadata': {                                                  │ │
│ │                   │   │   'RequestId': '9af51a6b-ac65-4fdc-92e0-edde962c55b6',               │ │
│ │                   │   │   'HTTPStatusCode': 403,                                             │ │
│ │                   │   │   'HTTPHeaders': {                                                   │ │
│ │                   │   │   │   'x-amzn-requestid': '9af51a6b-ac65-4fdc-92e0-edde962c55b6',    │ │
│ │                   │   │   │   'cache-control': 'no-cache, no-store',                         │ │
│ │                   │   │   │   'strict-transport-security': 'max-age=31536000;                │ │
│ │                   includeSubDomains',                                                        │ │
│ │                   │   │   │   'vary': 'accept-encoding',                                     │ │
│ │                   │   │   │   'content-type': 'text/xml;charset=UTF-8',                      │ │
│ │                   │   │   │   'transfer-encoding': 'chunked',                                │ │
│ │                   │   │   │   'date': 'Tue, 11 Oct 2022 04:26:50 GMT',                       │ │
│ │                   │   │   │   'server': 'AmazonEC2'                                          │ │
│ │                   │   │   },                                                                 │ │
│ │                   │   │   'RetryAttempts': 0                                                 │ │
│ │                   │   }                                                                      │ │
│ │                   }                                                                          │ │
│ │ request_context = {                                                                          │ │
│ │                   │   'client_region': 'us-east-1',                                          │ │
│ │                   │   'client_config': <botocore.config.Config object at 0x7f973b6d1a90>,    │ │
│ │                   │   'has_streaming_input': False,                                          │ │
│ │                   │   'auth_type': None,                                                     │ │
│ │                   │   'retries': {                                                           │ │
│ │                   │   │   'attempt': 1,                                                      │ │
│ │                   │   │   'invocation-id': 'b37d8858-c332-4b57-9290-f5fc90d11122',           │ │
│ │                   │   │   'max': 5                                                           │ │
│ │                   │   },                                                                     │ │
│ │                   │   'timestamp': '20221011T042650Z'                                        │ │
│ │                   }                                                                          │ │
│ │    request_dict = {                                                                          │ │
│ │                   │   'url_path': '/',                                                       │ │
│ │                   │   'query_string': '',                                                    │ │
│ │                   │   'method': 'POST',                                                      │ │
│ │                   │   'headers': {                                                           │ │
│ │                   │   │   'Content-Type': 'application/x-www-form-urlencoded;                │ │
│ │                   charset=utf-8',                                                            │ │
│ │                   │   │   'User-Agent': 'Boto3/1.24.89 Python/3.8.10 Linux/5.15.0-1019-aws   │ │
│ │                   Botocore/1.27.89'                                                          │ │
│ │                   │   },                                                                     │ │
│ │                   │   'body': {'Action': 'DescribeRegions', 'Version': '2016-11-15'},        │ │
│ │                   │   'url': 'https://ec2.us-east-1.amazonaws.com/',                         │ │
│ │                   │   'context': {                                                           │ │
│ │                   │   │   'client_region': 'us-east-1',                                      │ │
│ │                   │   │   'client_config': <botocore.config.Config object at                 │ │
│ │                   0x7f973b6d1a90>,                                                           │ │
│ │                   │   │   'has_streaming_input': False,                                      │ │
│ │                   │   │   'auth_type': None,                                                 │ │
│ │                   │   │   'retries': {                                                       │ │
│ │                   │   │   │   'attempt': 1,                                                  │ │
│ │                   │   │   │   'invocation-id': 'b37d8858-c332-4b57-9290-f5fc90d11122',       │ │
│ │                   │   │   │   'max': 5                                                       │ │
│ │                   │   │   },                                                                 │ │
│ │                   │   │   'timestamp': '20221011T042650Z'                                    │ │
│ │                   │   }                                                                      │ │
│ │                   }                                                                          │ │
│ │            self = <botocore.client.EC2 object at 0x7f973b6d19a0>                             │ │
│ │      service_id = 'ec2'                                                                      │ │
│ │    service_name = 'ec2'                                                                      │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯```

**Comment by sarahwooders** [comment]
Could you please try running `gcloud auth list`, and seeing what account is active? Then, for the active account, could you check the role that account (under "principal") has in the "IAM & Admin" -> "IAM" tab? For example, my active account is "wooders@berkeley.edu" which is shown as the owner: 

![image](https://user-images.githubusercontent.com/8505980/195003210-362521e8-22aa-4c43-b7a7-174b1f51f4cc.png)

Just wanted to check this since the error message is implying your GCP account doesn't have permissions to create a service account.

**Comment by sarahwooders** [comment]
For your AWS error, could you please check if the command `aws ec2 describe-regions` works for you? If that gets the same error, you may need to modify the policy attached to the IAM account you are using (as described here https://stackoverflow.com/questions/28222445/aws-cli-client-unauthorizedoperation-even-when-keys-are-set).

**Comment by dbickson** [comment]
HI @sarahwooders thanks for the helpful feedback! I was able to debug the aws issue, I had mulitple aws accounts I worked in the wrong one and managed to fix it by adding the policy. For google I added "Iam admin" policy into my user and getting another error: ````  Error saving GCP region config
    <HttpError 403 when requesting https://cloudresourcemanager.googleapis.com/v1/projects/flash-ward-346914:setIamPolicy?alt=json returned "Policy update access denied.". Details: "Policy update access denied.">
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/skyplane/cli/cli_impl/init.py", line 251, in load_gcp_config
    auth.save_region_config()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/skyplane/utils/imports.py", line 33, in wrapped
    return fn(*modules_imported, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/skyplane/compute/gcp/gcp_auth.py", line 32, in save_region_config
    service_account_credentials_file = self.service_account_credentials  # force creation of file
  File "/home/ubuntu/.local/lib/python3.8/site-packages/skyplane/compute/gcp/gcp_auth.py", line 68, in service_account_credentials
    self._service_account_email = self.create_service_account(self.service_account_name)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/skyplane/compute/gcp/gcp_auth.py", line 179, in create_service_account
    return retry_backoff(read_modify_write)  # retry loop needed for concurrent policy modifications
  File "/home/ubuntu/.local/lib/python3.8/site-packages/skyplane/utils/retry.py", line 30, in retry_backoff
    raise e
  File "/home/ubuntu/.local/lib/python3.8/site-packages/skyplane/utils/retry.py", line 27, in retry_backoff
    return fn()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/skyplane/compute/gcp/gcp_auth.py", line 176, in read_modify_write
    service.projects().setIamPolicy(resource=self.project_id, body={"policy": policy}).execute()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://cloudresourcemanager.googleapis.com/v1/projects/flash-ward-346914:setIamPolicy?alt=json returned "Policy update access denied.". Details: "Policy update access denied.">
```

**Comment by sarahwooders** [comment]
Glad you were able to fix the AWS issue! 

Would you be able to double check if the GCP account you're using has `iam.serviceaccounts.setiampolicy` and 
`resourcemanager.projects.setIamPolicy`? You can do this with the Policy Analyzer in IAM: 

![image](https://user-images.githubusercontent.com/8505980/195154938-0b17334d-835e-4849-af48-5ca5a28ed35e.png)

**Comment by dbickson** [comment]
Hi Sarah! Skyplane is finally working, I see a speedup of x3 copying 6TB from gs to local s3! Well done!!
Some minor comments:
- In the documentation it is written `$ skyplane [sync/cp] [local/s3/gcp/azure]://mybucket/big_dataset [local/s3/gcp/azure]://mybucket2/`
it should be gs and not gcp (otherwise I see a parsing error).
- What fixed it is that i killed the node and restarted it, I also had a double config trying both to give a json key file via `GOOGLE_APPLICATION_CREDENTIALS` as well as using ` gcloud auth login` which made a mess. i removed the `GOOGLE_APPLICATION_CREDENTIALS` and it worked (we have multiple users and it seems the json key policy refused to be for a specific user but was for some system gcloud user).

**Comment by sarahwooders** [comment]
Glad it's working! Just curious, which permission did you end up adding? 

Thanks for pointing these error out with the documentation! I definitely need to add more detailed instructions regarding how to set permissions and how to clear past credentials when switching between users.  

Also by local s3, do you mean a s3 bucket mount? We'd actually expect more than a 3X speedup so curious what your setup is.

**Comment by dbickson** [comment]
It may have been an overkill but I have added both:
<img width="275" alt="Screen Shot 2022-10-11 at 21 50 37" src="https://user-images.githubusercontent.com/4495523/195175082-340736e7-56bf-4330-b61b-1ec15f632361.png">
<img width="267" alt="Screen Shot 2022-10-11 at 21 50 51" src="https://user-images.githubusercontent.com/4495523/195175087-ce8b6e45-c0c8-4f75-801c-9e305cf9fa9e.png">

By local I meant copying from gs bucket into a local s3 compute node ssd drive. I can make some more tests but I got a speedup from 250mb/s to 750mb/s, when working locally inside google cloud i was getting 1Gb/s copying from gs bucket to local ssd drive inside google cloud.

**Comment by sarahwooders** [comment]
Ok good to know thanks! I'll close issue now that Skyplane's working, but please let us know on Slack or Github if you have more suggestions or feedback!
