### ISSUE TITLE
Need to verify configuration

### ISSUE THREAD

**Issue by ShishirPatil** [skyplane-project/skyplane#612]
Inspired by skypilot, there needs to be a `skyplane check` to verify if we have all the cloud configurations set-up. This can be useful to display to the user which clouds are enabled and which need reinitialization.

**Comment by parasj** [comment]
So Skypilot does not have an init phase, so they need to use `skypilot check` instead. Since we go through `skyplane init`, we don't need this. We do some basic verification that their cloud credentials are intact but otherwise error out during `skyplane init`.
