### ISSUE TITLE
[bug] Error running provision_gateway_instance: times out

### ISSUE THREAD

**Issue by liapassaglia** [skyplane-project/skyplane#626]
**Bug Description**
Error running provision_gateway_instance: is not ready in 120 seconds

**To Reproduce**
Command ran: skyplane cp -r s3://lias-aws-bucket gs://lias-gcs-bucket

**Screenshots**

**Transfer client log**
![image](https://user-images.githubusercontent.com/60628548/197049059-583348e5-a46b-4cf8-a305-57aacc5bc2ec.png)

**Environment info (please complete the following information):**
 - OS: Mac OS
- Python version 3.10

**Additional context**
VMs are created in both GCP and AWS. 
GCP logs show an SSH error so I believe the time out occurs because unable to connect to VM. 
AWS deprovisioning is failing (unsure if related)

**Comment by parasj** [comment]
From Slack: `Invalid ssh key entry - unrecognized format: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCn6phnIpvBslsvWT6iY2+apz4QLjuazE8AqJnjNfPD4ZKnuYRD`

**Comment by parasj** [comment]
I'm not able to reproduce this issue locally. I tried `skyplane cp -r s3://imagenet-bucket gs://exps-paras-skylark-us-east1-b/fakeimagenet_2`.

One thing worth trying is to delete the GCP locally and try regenerating it:
```
rm -rf ~/.skyplane/keys/gcp
skyplane init --reinit-gcp
skyplane cp -r ...
skyplane deprovision
```

If that doesn't work, please DM me the contents of the key under `~/.skyplane/keys/gcp` on the Skyplane Slack.
