### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by ra312** [skyplane-project/skyplane#631]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (please include the full Skyplane command you ran):

**Expected behavior**

**Screenshots**

**Transfer client log**
In the log output from Skyplane, please upload the debug log from the CLI. You can find the file in the log output:
![](https://gist.githubusercontent.com/parasj/d17850dff9605d33f3507213fb62b672/raw/5cc8a9b9d6c0b4f4f01582c03c4f6d7af10594f7/github_issue_template_client_log.png)

**Environment info (please complete the following information):**
 - OS: [e.g. Mac OS, Linux]
- Python version

**Additional context**

**Comment by ra312** [comment]
Cool research, using template to bookmark project from my phone

**Comment by parasj** [comment]
@ra312 Thanks! I am closing this issue, but am excited you are interested in the project.
