### ISSUE TITLE
[api] Non-owned endpoints are not yet supported

### ISSUE THREAD

**Issue by parasj** [skyplane-project/skyplane#674]
The API does not support buckets like `s3://imagenet-bucket` yet.

**Comment by parasj** [comment]
Hey @abiswal2001 I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/skyplane-636ede193e484c0010b5c46f/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by sarahwooders** [comment]
Is this still an issue?

**Comment by parasj** [comment]
@abiswal2001 With the CLI, can you check if this bucket works?
