### ISSUE TITLE
benchmarking agains fpart, rclone ?

### ISSUE THREAD

**Issue by truatpasteurdotfr** [skyplane-project/skyplane#726]
Hello 

You have benchmarked against rsync but what would skyplane compare with fpart (http://www.fpart.org/fpart/ ) or objet data movers such as rclone (https://rclone.org/ ) ?

Best regards

Tru

**Comment by sarahwooders** [comment]
Skyplane will create multiple VM instances to execute large data transfers in parallel across multiple machines, while I believe tools like rclone still run transfers from your local machine but provide a unified interface. So you would probably see similar performance gains with Skyplane over the AWS CLI and rclone (up to 110X) depending on your object sizes and the number of VMs you use with Skyplane.

**Comment by truatpasteurdotfr** [comment]
ok thanks for your input, closing the issue.

Best regards

Tru
