### ISSUE TITLE
Feature: SCP (Samsung Cloud Platform) Support Contribution

### ISSUE THREAD

**Issue by sangjun-kang** [skyplane-project/skyplane#925]
## Overview
I have developed code to support [SCP (Samsung Cloud Platform)](https://cloud.samsungsds.com/serviceportal/index.html) and would like to contribute it. I have completed testing and followed all the procedures in the contributing guide.

## Details
- **Contributor:** sangjun-kang (aau213)
- https://github.com/skypilot-sds/skyplane/tree/scp-contribution
- **Branch:** scp-contribution

## Progress
- Code development and testing completed
- Issue and discussion registration

## Notes
- This feature introduces support for SCP, and I have followed the contributing guide for the required tasks.
- Initiating a discussion on the related work.

Upon confirmation, I will create the scp-contribution branch and submit a pull request.

**Comment by sarahwooders** [comment]
Closed by #926
